"""
ECDT - Phase 5
Observer Agent models.

This module defines the cognitive-layer representations used to
transform Phase 2 anomaly events into structured incidents.

Pipeline:

    AnomalyEvent
          |
          v
    AnomalyInput
          |
          v
       Incident
          |
          v
    IncidentContext
          |
          v
    Diagnostic / Impact Agent
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any

from ...ingestion.models import (
    DetectionMethod,
    IncidentType,
)


class IncidentStatus(str, Enum):
    """Lifecycle state of an observed incident."""

    DETECTED = "detected"


class IncidentSeverity(str, Enum):
    """Severity assigned by the Observer Agent."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class IncidentSource(str, Enum):
    """Origin of the incident."""

    OBSERVER = "ECDT_OBSERVER"


@dataclass(slots=True)
class AnomalyInput:
    """
    Normalized input received by the Observer Agent.

    This model represents an anomaly coming from the Phase 2
    anomaly detection layer.
    """

    event_id: str
    case_id: str
    timestamp: int

    resource_id: str

    signal_type: str
    metric_name: str

    value: float
    score: float

    detection_method: DetectionMethod

    incident_type: IncidentType | None = None

    threshold: float | None = None

    metadata: dict[str, Any] = field(
        default_factory=dict
    )


@dataclass(slots=True)
class Incident:
    """
    Structured incident generated by the Observer Agent.

    The Observer identifies and qualifies the incident but does
    not determine its root cause.
    """

    incident_id: str

    case_id: str

    incident_type: IncidentType

    status: IncidentStatus

    severity: IncidentSeverity

    resource_id: str

    detected_at: int

    signal_type: str
    metric_name: str

    observed_value: float
    anomaly_score: float

    detection_method: DetectionMethod

    confidence: float

    source: IncidentSource = IncidentSource.OBSERVER

    metadata: dict[str, Any] = field(
        default_factory=dict
    )


@dataclass(slots=True)
class IncidentContext:
    """
    Structured context returned by the Observer and passed to the future
    Diagnostic/Impact Agent.

    This model intentionally separates:

    - incident qualification,
    - temporal context,
    - graph context.

    Root-cause reasoning is not performed by this model.
    """

    incident: Incident

    resource_id: str

    detection_timestamp: int

    signal_type: str
    metric_name: str

    observed_value: float
    anomaly_score: float

    temporal_context: dict[str, Any] | TemporalContext = field(
        default_factory=dict
    )

    graph_context: dict[str, Any] = field(
        default_factory=dict
    )

    metadata: dict[str, Any] = field(
        default_factory=dict
    )

    qualification: dict[str, Any] = field(
        default_factory=dict
    )

    persisted: bool = False

    incident_id: str | None = None

    case_id: str | None = None
    
@dataclass(slots=True)
class TemporalContext:
    """
    Temporal context retrieved from TimescaleDB around an anomaly.

    The context is intended to be consumed by downstream cognitive
    components such as the Diagnostic/Impact Agent.
    """

    resource_id: str

    metric_name: str

    signal_type: str

    anomaly_timestamp: int

    window_before_seconds: int

    window_after_seconds: int

    rows_retrieved: int = 0

    numeric_observation_count: int = 0

    requested_start_timestamp: float | None = None

    requested_end_timestamp: float | None = None

    requested_duration_seconds: float | None = None

    first_observation_timestamp: float | None = None

    last_observation_timestamp: float | None = None

    actual_coverage_duration_seconds: float | None = None

    estimated_sampling_interval_seconds: float | None = None

    expected_observation_count: int | None = None

    observed_unique_timestamp_count: int = 0

    missing_observation_count: int | None = None

    temporal_data_completeness_ratio: float | None = None

    observations: list[dict[str, Any]] = field(
        default_factory=list
    )

    statistics: dict[str, Any] = field(
        default_factory=dict
    )
